import React, { useState } from 'react';
import { generateStory } from '../services/gemini';
import { Language } from '../types';
import { BookOpen, RefreshCw, Loader2, Sparkles } from 'lucide-react';

export const Stories: React.FC = () => {
  const [language, setLanguage] = useState<Language>(Language.ENGLISH);
  const [content, setContent] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [topic, setTopic] = useState('Lord Krishna');

  const handleGenerate = async () => {
    setLoading(true);
    const story = await generateStory(language, topic);
    setContent(story);
    setLoading(false);
  };

  return (
    <div className="space-y-6">
      <div className="bg-gradient-to-r from-orange-100 to-amber-50 p-6 rounded-xl border border-orange-200">
        <div className="flex items-center gap-3 mb-4">
          <BookOpen className="text-primary w-8 h-8" />
          <h2 className="text-2xl font-bold text-gray-800">Sacred Wisdom</h2>
        </div>
        <p className="text-gray-700 mb-6">
          Immerse yourself in the divine teachings of the Bhagavad Gita and stories of Lord Krishna.
        </p>

        <div className="flex flex-wrap gap-4 mb-6">
          <select 
            value={language} 
            onChange={(e) => setLanguage(e.target.value as Language)}
            className="px-4 py-2 rounded-lg border border-orange-200 bg-white focus:outline-none focus:ring-2 focus:ring-primary"
          >
            <option value={Language.ENGLISH}>English</option>
            <option value={Language.TELUGU}>Telugu</option>
          </select>

          <select 
            value={topic} 
            onChange={(e) => setTopic(e.target.value)}
            className="px-4 py-2 rounded-lg border border-orange-200 bg-white focus:outline-none focus:ring-2 focus:ring-primary"
          >
            <option value="Lord Krishna">Stories of Lord Krishna</option>
            <option value="Bhagavad Gita Karma Yoga">Karma Yoga (Gita)</option>
            <option value="Bhagavad Gita Bhakti Yoga">Bhakti Yoga (Gita)</option>
            <option value="Dharma">Concept of Dharma</option>
          </select>

          <button
            onClick={handleGenerate}
            disabled={loading}
            className="flex items-center gap-2 bg-primary hover:bg-amber-600 text-white px-6 py-2 rounded-lg font-medium transition-colors disabled:opacity-50"
          >
            {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
            {loading ? 'Consulting the Scriptures...' : 'Read Story'}
          </button>
        </div>

        {content && (
          <div className="bg-white p-6 rounded-lg shadow-sm border border-orange-100 animate-fade-in relative">
             <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-primary to-orange-300 rounded-t-lg"></div>
            <h3 className="text-lg font-semibold text-primary mb-3 uppercase tracking-wide flex items-center gap-2">
              <Sparkles className="w-4 h-4" />
              Divine Insight
            </h3>
            <div className="prose prose-orange max-w-none text-gray-800 leading-relaxed whitespace-pre-line">
              {content}
            </div>
            <div className="mt-4 flex justify-end">
              <span className="text-xs text-gray-400 italic">Generated by Gemini AI</span>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};